[package]
name = "env_config"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
dotenv = "0.15.0"
anyhow = "1"
askama = "0.11.1"           # Type-safe, compiled Jinja-like templates for Rust
convert_case = "0.6.0"      # Convert a string to snake_case, kebab-case, or camelCase
