[package]
name = "env_config"
version = "0.1.0"
edition = "2021"
authors = [
  "Hengfei Yang <hengfei.yang@gmail.com>",
]
homepage = "https://github.com/zinclabs/env-config/"
repository = "https://github.com/zinclabs/env-config/"
documentation = "https://docs.rs/env_config"
keywords = ["environment", "env", "dotenv", "settings", "config"]
readme = "README.md"
license = "MIT"

[[examples]]
name = "config"

[lib]
proc-macro = true

[dependencies]
dotenv = "0.15.0"
anyhow = "1"
askama = "0.11.1"           # Type-safe, compiled Jinja-like templates for Rust
convert_case = "0.6.0"      # Convert a string to snake_case, kebab-case, or camelCase
