name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: dtolnay/rust-toolchain@stable
    - name: Install Rust tools
      run: |
        rustup component add rustfmt clippy
        cargo install cargo-audit cargo-outdated
    - name: Check formatting
      run: cargo fmt -- --check

    - name: Lint with clippy
      run: cargo clippy -- -D warnings

    - name: Audit dependencies
      run: cargo audit

    - name: Check for outdated dependencies
      run: cargo outdated

    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose
